name: Main branch
on:
  push:
    branches: [ itisopen ]

permissions:
  contents: write

jobs:
  perform:
    uses: itisopen/github-actions-workflows-github-action-composite/.github/workflows/main-branch.yml@itisopen
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
    secrets:
      github-private-actions-pat: "${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}"
